# Generated by Django 5.1.3 on 2024-11-10 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTrackApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseadd',
            name='expense_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
