# Generated by Django 5.1.3 on 2024-11-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTrackApp', '0002_expenseadd_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseadd',
            name='expense_date',
            field=models.DateField(),
        ),
    ]
